eureka:
  client:
    serviceUrl:
      # eureka服务端提供的注册地址 参考服务端配置的这个路径
      defaultZone: http://eureka:3000/eureka,http://eureka1:3001/eureka,http://eureka2:3002/eureka
  instance:
    # 此实例注册到eureka服务端的唯一的实例ID
    instance-id: zuul-0
    # 是否显示IP地址
    prefer-ip-address: true
    # eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseRenewalIntervalInSeconds: 1
    # Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    leaseExpirationDurationInSeconds: 3

spring:
  application:
    # 此实例注册到eureka服务端的name
    name: client-zuul
server:
  port: 8003

zuul:
  # 禁止所有服务使用服务名称访问
  ignored-services: "*"
  # 添加访问前缀
  prefix: /api
  # 前缀默认会从请求路径中移除，当 strip-prefix: true 时（会移除）false不移除
  strip-prefix: true
  routes:
    goods:
      # 自己定义的名称,网关服务
      serviceId: zuul-server
      # /* 是一级 /** 是多级
      path: /zuul/**