server:
  port: 3000
eureka:
  server:
    # 关闭自我保护机制
    enable-self-preservation: false
    # 设置清理间隔（单位：毫秒 默认是60*1000）
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: localhost

  client:
    # 不把自己作为一个客户端注册到自己身上
    registerWithEureka: false
    # 不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己注册了）
    fetchRegistry: false
    # 微服务要注册到的地址
    serviceUrl:
      # http://localhost:3000/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka