server:
  port: 3002

eureka:
  server:
    #关闭自我保护机制
    enable-self-preservation: false
    #设置清理间隔（单位：毫秒 默认是60*1000）
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: eureka2

  client:
    #把自己作为一个客户端注册到自己身上
    registerWithEureka: true
    #要从服务端获取注册信息
    fetchRegistry: true
    serviceUrl:
      #微服务要注册到的地址
      defaultZone: http://eureka:3000/eureka,http://eureka1:3001/eureka

spring:
  application:
    name: eurekaServer